#在这里配置你的数据库，默认用户名密码为root，默认仓库名称为demo，可以自行配置以进行调试
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/how2java?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis会在resources的mapper目录下寻找xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml

#端口为8081
server:
  port: 8081
